### ISSUE TITLE
No updated to upstream version!

### ISSUE THREAD

**Issue by jedie** [YunoHost-Apps/psitransfer_ynh#10]
Latest upstream version is **v2.1.1** but this package ships **v2.0.1**: 

https://github.com/YunoHost-Apps/psitransfer_ynh/blob/3f2e0149d9a6de526901e25444f731898f921b7d/conf/app.src#L1

And the manifest has Version **v1.12.0**:
https://github.com/YunoHost-Apps/psitransfer_ynh/blob/3f2e0149d9a6de526901e25444f731898f921b7d/manifest.json#L9

**Comment by ericgaspar** [comment]
fixed with #11
