### ISSUE TITLE
How to increase max file size limits?

### ISSUE THREAD

**Issue by jedie** [YunoHost-Apps/psitransfer_ynh#6]
I just change the `/var/www/psitransfer/config.production.js` and increase the file size limits. But it doesn't work:

![grafik](https://user-images.githubusercontent.com/71315/193575907-7dbd6797-1c53-4bdd-91fa-72c7d69ff412.png)

Think it's a limitation of nginx, isn't it?

EDIT: Yes, i have to add client_max_body_size into: https://github.com/YunoHost-Apps/psitransfer_ynh/blob/master/conf/nginx.conf But i think this should be also change via user config panel, isn't it?

And the question is, what's the best size here?!? The upload happend in chunks, isn't it?
EDIT2: The chunk size is 4,77MB ... So `client_max_body_size 5M;` may be a good choice.

**Comment by ericgaspar** [comment]
fixed with #11
